# 白名单，只记录这个人，优先级最高 例['用户名1', '用户名2', ...]
white_list: []
# 黑名单，不记录这个人，优先级第二高 例['用户名1', '用户名2', ...]
black_list: []
# 最低卡片等级，小于这个等级的跳过不记录，如果为空则全量抓取
min_card_level: 850
# 默认对手争夺等级，当对手为850满级卡且未读取到论坛系数时的争夺等级，目前最高争夺加成等级为2000
max_kf_level: 1400
# 自身争夺等级，当分析战斗记录时，用于计算进攻等级差带来的伤害影响，目前最高争夺加成等级为2000
my_kf_level: 1400
# 段位强化等级 正数强化对方 负数强化自身 当分析战斗记录时，此项影响对方伤害计算
rank_level: 2
# 自身技能、暴击抵抗，同上用于分析战斗记录，目前上限为3
skl_def: 0
crt_def: 0
# 时间范围，如果为空则全量抓取，因为3s环境变化较快不建议设置太久远
start_date: '2025-01-01'
end_date: ''
# 段位限制，只分析此段位的出击记录，填空字符串为不限制，注意此选项需要最新版收割机的支持
rank_limit: 'SSS'
# 对手护符配置，格式 角色_武器: 护符或角色: 护符，当未精确匹配到武器时使用角色的护符，都未匹配使用default属性的值
amulet_config:
  default: 'SKL 10 PDEF 10 MDEF 10 AAA 8'
  MO: 'AGI 20 INT 80 SPR 80 MATK 10 SLD 10 REC 10 LCH 10 RFL 10 SKL 10 PDEF 10 MDEF 10 AAA 8'
  LIN: 'STR 80 VIT 80 MND 80 HP 10 SPD 10 PATK 10 SKL 10 REC 10 LCH 10 RFL 10 CRT 10 PDEF 10 MDEF 10 AAA 8'
  AI: 'AGI 80 INT 80 VIT 80 MND 80 HP 10 SPD 10 REC 10 LCH 10 RFL 10 SKL 10 CRT 10 PDEF 10 MDEF 10 AAA 8'
  WEI: 'AGI 80 INT 80 VIT 60 MND 60 HP 10 SPD 10 SLD 10 REC 10 LCH 10 CRT 10 SKL 10 AAA 8'
  MING: 'STR 60 AGI 60 INT 60 VIT 60 MND 60 HP 10 REC 10 LCH 10 PATK 10 SPD 10 RFL 10 CRT 10 SKL 10 PDEF 10 MDEF 10 AAA 8'
  MIN: 'STR 80 VIT 80 MND 80 HP 10 PATK 10 SPD 10 REC 10 LCH 10 SKL 10 CRT 10 PDEF 10 MDEF 10 AAA 8'
  MENG: 'AGI 80 INT 80 SPR 80 SLD 10 SPD 10 MATK 10 REC 10 LCH 10 RFL 10 CRT 10 SKL 10 AAA 8'
  XI: 'STR 80 AGI 80 VIT 80 MND 80 HP 10 PATK 10 SPD 10 REC 10 LCH 10 RFL 10 CRT 10 SKL 10 PDEF 10 MDEF 10 AAA 8'
  YI: 'STR 80 AGI 20 VIT 80 MND 80 HP 10 PATK 10 SPD 10 REC 10 LCH 10 RFL 10 CRT 10 SKL 10 PDEF 10 MDEF 10 AAA 8'
  XIA: 'AGI 80 INT 60 SPR 80 VIT 60 MND 60 HP 10 SLD 10 REC 10 LCH 10 SPD 10 MATK 10 CRT 10 SKL 10 RFL 10 AAA 8'
  WU: 'STR 80 AGI 80 VIT 80 MND 80 HP 10 SPD 10 PATK 10 REC 10 LCH 10 RFL 10 CRT 10 PDEF 10 MDEF 10 AAA 8'
  YA: 'STR 80 AGI 80 INT 80 VIT 60 MND 60 HP 10 SPD 10 REC 10 LCH 10 PATK 10 CRT 10 SKL 10 PDEF 10 MDEF 10 AAA 8'
# 默认许愿池
wish_config: '100 100 100 100 100 500 500 500 500 100 100 100 100 100'
# 默认成长值
default_g: 100000
# 是否加入权重，会根据出现次数加入w值，目前匹配池不平均建议开启
is_add_w: true
# 指定雅的模式 0白天1黑夜
ya_mode: 1


# 以下是从论坛获取系数的配置，由于目前基础属性高度依赖争夺等级，建议开启
# 是否通过用户的论坛发帖记录以及系数排行获取真实系数，关闭此项则默认按照max_kf_level的值处理
# 注意开启此项虽然使等级相关计算更加精准但是会极大的拖慢程序，考虑到咕咕镇服务器的抗压能力强烈建议开启时一天只跑一次
is_search_level: false
# 当is_search_level开启时，需要登录才可以搜索，由于搜索次数的限制（系数*5+20）请确保自身账号的系数和等级分足够
# 目前仅支持https://kf.miaola.work域名的cookie
cookie: ''
# 当is_search_level开启时，对方的幻影等级
shadow_level: 450
# 当is_search_level开启时，网络请求时的代理地址，由于咕咕镇机房部署在国外，建议使用代理提升访问速度
# 注意仅支持http代理，例'http://127.0.0.1:1081'，填空不做代理
proxy_url: ''
# 是否从目录level.db缓存中读取系数，建议开启此项，会有效缓解网络开销
# 但是需要注意时效性，随着时间的推移缓存的系数会相对越低，建议隔一个月关闭此选项刷新缓存
use_cache: true

# 是否分析战斗记录，目前仅支持分析对手第一次出手的物伤（推测力量）和魔伤（推测智力），注意开启此选项并不会使推测结果变得精确
# 由于有些角色技能比较特殊，伊无法分析，希雅只能分析魔伤，霞默冥只能分析物伤
# 自身是雅时默认为黑夜雅触发对手降攻，如果记录中存在自身是雅且在白天出击请关闭开关
is_analyse_battle: false
# 以下是点数推测箭头配比，瞎改会导致推测的点数非常离谱，请根据自身对环境的理解谨慎修改
# 单上+双上箭头 双上箭头的占比 此值必须大于0.5小于0.8
vm_prop_udu: 0.7
# 单下+双上箭头 双上箭头的占比 此值必须大于0.67小于0.9
vm_prop_ddu: 0.75
# 单下+单上箭头 单上箭头的占比 此值必须大于0.5小于0.8
vm_prop_du: 0.65
# 力量敏捷智力根据箭头占比分配
# 敏捷双上 力量或智力也双上箭头时 敏捷在剩余点数中的占比 此值必须大于0.4小于0.6
agi_prop_dudu: 0.55
# 敏捷双上 力量或智力上箭头时 敏捷在剩余点数中的占比 此值必须大于0.5小于0.8
agi_prop_duu: 0.6
# 敏捷双上 力量或智力下箭头时 敏捷在剩余点数中的占比 此值必须大于0.67小于0.9
agi_prop_dud: 0.8
# 敏捷单上 敏捷在全部点数中的占比，此值必须大于0.2小于等于0.4
agi_prop_u: 0.35
# 敏捷单下 敏捷在全部点数中的占比，此值必须大于0.1小于等于0.2
agi_prop_d: 0.2
# 敏捷双下 敏捷在全部点数中的占比，此值必须大于0小于等于0.1
agi_prop_dd: 0.001
# 推测完敏捷，开始推测智力，注意由于有校验机制无需担心点数溢出
# 智力双上 智力在全部点数中的占比，此值必须大于0.4小于1
int_prop_du: 0.999
# 智力单上 智力在全部点数中的占比，此值必须大于0.2小于等于0.4
int_prop_u: 0.4
# 智力单下 智力在全部点数中的占比，此值必须大于0.1小于等于0.2
int_prop_d: 0.2
# 智力双下 智力在全部点数中的占比，此值必须大于0小于等于0.1
int_prop_dd: 0.001


# 下面的设置最好不要乱动，除非你对游戏以及源码有足够的了解
# 卡片映射
card_map:
  默: 'MO'
  琳: 'LIN'
  艾: 'AI'
  梦: 'MENG'
  薇: 'WEI'
  冥: 'MING'
  命: 'MIN'
  伊: 'YI'
  希: 'XI'
  舞: 'WU'
  霞: 'XIA'
  雅: 'YA'
# 天赋映射
talent_map:
  启程之誓: 'SHI'
  启程之心: 'XIN'
  启程之风: 'FENG'
  等级挑战: 'TIAO'
  等级压制: 'YA'
  破壁之心: 'BI'
  破魔之心: 'MO'
  复合护盾: 'DUN'
  鲜血渴望: 'XUE'
  削骨之痛: 'XIAO'
  圣盾祝福: 'SHENG'
  恶意抽奖: 'E'
  伤口恶化: 'SHANG'
  精神创伤: 'SHEN'
  铁甲尖刺: 'CI'
  忍无可忍: 'REN'
  热血战魂: 'RE'
  点到为止: 'DIAN'
  午时已到: 'WU'
  纸薄命硬: 'ZHI'
  沸血之志: 'FEI'
  波澜不惊: 'BO'
  飓风之力: 'JU'
  红蓝双刺: 'HONG'
  荧光护盾: 'JUE'
  后发制人: 'HOU'
  钝化锋芒: 'DUNH'
  自信回头: 'ZI'
  不动如山: 'SHAN'
  致命节奏: 'ZOU'
  往返车票: 'PIAO'
  天降花盆: 'PEN'
# xpath设置
xpath_config:
    attr: '//div[contains(@class,''alert-info'')]/div//span[contains(@class,''label-outline'')]//text()'
    attr2: '//div[contains(@class,''alert-info'')]/div//span[contains(@class,''label-outline'')]//i/@class'
    talent: '//div[contains(@class,''alert-info'')]/div//div[contains(@class,''fyg_tr'')]//text()'
    mytalent: '//div[contains(@class,''alert-danger'')]/div//div[contains(@class,''fyg_tr'')]//text()'
    gear: '//button[contains(@class,''fyg_colpzbg'')]/@data-original-title'
    level: '//button[contains(@class,''fyg_colpzbg'')]//text()'
    color: '//button[contains(@class,''fyg_colpzbg'')]/@style'
    mycolor: '//button[contains(@class,''fyg_colpzbg'')]/@style'
    search: '//table[contains(@class,''thread1'')]//tr[3]/td[1]/a/@href'
    read: '//div[contains(@class,''readtext'')]//td[1]//a[1]/@href'
    info: '//table[contains(@class,''log1'')]//tr[2]/td[2]//text()'
    hp: '//div[contains(@class,''alert-info'')]/div//span[contains(@class,''label-danger label-outline'')]//text()'
    sld: '//div[contains(@class,''alert-info'')]/div//span[contains(@class,''label-info label-outline'')]//text()'
    myhp: '//div[contains(@class,''alert-danger'')]/div//span[contains(@class,''label-danger label-outline'')]//text()'
    mysld: '//div[contains(@class,''alert-danger'')]/div//span[contains(@class,''label-info label-outline'')]//text()'
    top: '//tr[contains(@onmouseover,''this.style.backgroundColor'')]'
    mycard: '//span[contains(@class,''fyg_f18'')]/text()'
# 正则设置
match_config:
    str: "(?<=).*?(?=力)"
    agi: "(?<=力).*?(?=敏)"
    int: "(?<=敏).*?(?=智)"
    vit: "(?<=智).*?(?=体)"
    spr: "(?<=体).*?(?=精)"
    mnd: "(?<=精).*?(?=意)"
    talent: "(?<=\\|).*?(?=\\|)"
    color: ".*/(.*)\\.gif.*"
# 输入文件路径
input_path: './source/'
# 输出文件路径
output_path: './source/pc.txt'
# 通用请求头
headers:
  Content-Type: 'application/x-www-form-urlencoded'
  Accept: 'text/html,application/xhtml+xml,application/xml;q=0.9,image/avif,image/webp,image/apng,*/*;q=0.8,application/signed-exchange;v=b3;q=0.7'
  Accept-Encoding: 'gzip, deflate, br, zstd'
  Accept-Language: 'zh-CN,zh;q=0.9'
  User-Agent: 'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/126.0.0.0 Safari/537.36'
# 论坛地址配置
url_config:
  search: '/search.php'